schema_version: 1

context:
  version: "0.1.13"

package:
  name: qualibrate-config
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/q/qualibrate-config/qualibrate_config-${{ version }}.tar.gz
  sha256: b353c8986583177d86523adc5630144ca4a1fa9651d93ae17d406b91e9a16e7e

build:
  noarch: python
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - qualibrate-config = qualibrate_config.__main__:main

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }}
    - pydantic >=2.9.2,<3.0.0
    - jsonpatch >=1.33.0,<2.0.0
    - tomli >=2.0.1,<3.0.0
    - tomli-w >=1.0.0,<2.0.0
    - pydantic-settings >=2.6.1,<3.0.0
    - click >=8.1.7,<9.0.0,<8.2.0

tests:
  - python:
      imports:
        - qualibrate_config
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - qualibrate-config --help

about:
  summary: Configuration for Qualibrate
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://pypi.org/project/qualibrate-config/

extra:
  recipe-maintainers:
    - noya-gol
